services:
  db:
    image: postgres
    container_name: commons-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - commons_data:/var/lib/postgresql/data

volumes:
  commons_data:
